import os

# TODO: use env vars for all of these
DATABASE_URL = "sqlite:///unipick.db"
WEBSERVER_HOST = "0.0.0.0"
WEBSERVER_PORT = 8000
WEBSERVER_THREADS = 4
WEBSERVER_CONNECTION_LIMIT = 100

JWT_ENCRYPT_KEY = os.environ.get("JWT_ENCRYPT_KEY", "a" * 32)
JWT_DECRYPT_KEY = os.environ.get("JWT_DECRYPT_KEY", JWT_ENCRYPT_KEY)
JWT_ALGORITHM = "HS256"
JWT_TTL = 900
BCRYPT_ROUNDS = 16
