DATABASE_URL = "sqlite:///unipick.db"
WEBSERVER_HOST = "0.0.0.0"
WEBSERVER_PORT = 8000
WEBSERVER_THREADS = 4
WEBSERVER_CONNECTION_LIMIT = 100

JWT_ENCRYPT_KEY = "a" * 32
JWT_ALGORITHM = "HS256"
JWT_TTL = 900
