[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "unipick"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["."]

[tool.ruff]
lint.select = ["F", "I"]  # F401 = unused imports
fix = true

[tool.ruff.format]
quote-style = "double"

[tool.black]
line-length = 88

[tool.mypy]
strict = true
exclude = "^(venv|tests)/"
mypy_path = "typings"

[tool.pytest]
strict = true
console_output_style = "progress"

[[tool.mypy.overrides]]
module = "jdatetime.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "common.configs"
disable_error_code = ["call-arg"]
